<a href="https://colab.research.google.com/github/elfabry88/SIM_YAC_SUAREZ_UPSE2023/blob/main/EJERCICIO110623.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [157]:
import numpy as np
import math

In [158]:
L=10000
dx=2500
Tiempo=100000
DT=1
K=50 # Permeabilidad en mD 
Por=0.2
vis=1 # Viscosidad en Centipoise
Beta=1 #Factor volumetrico
CompTotal= 1**-6 #Compresibilidad Total en psi**-1
A=200000 #Area ft2

In [159]:
Alpha=K/(vis*Por*CompTotal)
Alpha

250.0

In [160]:
Eta=Alpha*DT/dx**2
Eta

4e-05

In [161]:
#ESQUEMA EXPLICITO
def Presdt(P0,P1,P2,Eta):
  Pdt=P1*Eta*(P0-2*P1+P2)
  return(Pdt)

Pexplicita=np.zeros((Tiempo//DT,L//dx)) #Crear Matriz vacia que guardara los resultados

In [162]:
#Condiciones iniciales
Pyac=1000
Piz=2000
Pder=0
Pin=np.ones(L//dx)
Pres=np.zeros(L//dx)
Pin=Pin*Pyac
Pin[0]=Piz
Pin[len(Pin)-1]=Pder
Pin

array([2000., 1000., 1000.,    0.])

In [163]:
t=DT
Pexplicita[0]=Pin #los valores de la columna [0] van a guardarse los valores de Pin
Pexplicita.shape
while t<Tiempo:
  for i in range(0,len(Pin)-1):
    if i==0:
      Pres[i]=Pin[0]
    elif i==len(Pin)-1:
      Pres[i]=Pin[len(Pin)-1]
    else:
      Pres[i]=Presdt(Pin[i-1],Pin[i],Pin[i+1],Eta)
  Pexplicita[t//DT]=Pres
  t=t+DT
  Pin=Pres


In [164]:
Pexplicita

array([[ 2.000000e+03,  1.000000e+03,  1.000000e+03,  0.000000e+00],
       [ 2.000000e+03,  4.000000e+01, -4.000000e+01,  0.000000e+00],
       [ 2.000000e+03,  3.008000e+00, -1.328128e-01,  0.000000e+00],
       ...,
       [ 2.000000e+03,  0.000000e+00, -0.000000e+00,  0.000000e+00],
       [ 2.000000e+03,  0.000000e+00, -0.000000e+00,  0.000000e+00],
       [ 2.000000e+03,  0.000000e+00, -0.000000e+00,  0.000000e+00]])

In [165]:
#ESQUEMA IMPLICITO
Pimplicita=np.zeros((Tiempo//DT,L//dx))

Pin=np.ones(L//dx)
Pres=np.zeros(L//dx)
Pin=Pin*Pyac
Pin[0]=Piz
Pin[len(Pin)-1]=Pder
N=L//dx
Matriz_resolucion=np.zeros([N-2,N-2])

In [166]:
for i in range(N-2): #porque siempre se resta 2 al total de la matriz la cantidad de triangulos q tendremos
  Matriz_resolucion[i,i]=1+2*Eta #I es igual a J por eso se pone [i,i] - se llena la diagonal (1,2)(2,2)(3,3)(4,4)(5,5) etc
  if i>0:
    Matriz_resolucion[i,i-1]=-Eta #Llenar los valores a la izquierda de la diagonal con -Eta
  if i<(N-3):
    Matriz_resolucion[i,i+1]=-Eta #Llenar los valores a la derecha de la diagonal - N-2 no tiene valores a la derecha pero en N-3 si tiene valores y se pone -eta


In [167]:
Pcal=np.zeros([N-2]) #
Pcal=np.linalg.solve(Matriz_resolucion,Pin[1:-1])

In [ ]:
Pcal

array([999.9600016, 999.9600016])

In [ ]:
Pder

0

In [168]:
np.concatenate

([2000], array([999.9600016, 999.9600016]), [0])

In [169]:
Pres=np.concatenate([Piz],Pcal,[Pder])
Pres

TypeError: ignored

In [ ]:

Pimplicita[0]=Pin
t=DT
while t<Tiempo:
  Pcal=np.linalg.solve(matriz_resolucion,Pin[1:-1])
  Pres=np.concatenate([Piz],Pcal,[Pder])

NameError: ignored